name: Test SSH

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: T530

    steps:
      - name: Test connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Połączono poprawnie"
            whoami
            hostname
            uptime
